const GET_TOTAL = 'GET_TOTAL'
const GET_COLCONTENT = 'GET_COLCONTENT'
const GET_PHOTOSDEFAULT ='GET_PHOTOSDEFAULT'
const CREATE_PHOTOS = 'CREATE_PHOTOS'
const GET_CONTENTBYID = 'GET_CONTENTBYID'
const GET_APPDYNAMIC = 'GET_APPDYNAMIC'

export default {
    GET_TOTAL,
    GET_COLCONTENT,
    GET_PHOTOSDEFAULT,
    CREATE_PHOTOS,
    GET_CONTENTBYID,
    GET_APPDYNAMIC
}

